### ISSUE TITLE
How can we change the API Keys?

### ISSUE THREAD

**Issue by MapGuy11** [mewtek/OpenStar#5]
Hello,

I love your project I still have working weather.com API keys and was wondering how to change the ones hardcoded into the emulator to my own. Also if you want to find your own and need help let me know.

Thanks.

**Comment by mewtek** [comment]
i havent worked on this project in a while, but i think you'd have to completely re-compile the emulator and change the API key present in ``OSSettings.hx``, replacing the old API key with your current one.

Also, if you're willing to send over a new key, go ahead and shoot me a dm on disc: mewtek#9099
